import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

export const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my website!
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>Hello world</code>
        </p>

      </main>
    </div>
  );
};
