name: CI/CD
on:
  push:
    branches: [master, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing devDependencies
        run: npm install
      - name: Lint
        run: |
          "npm run lint"
          "npm run format",
          "npm run fix-lint",
          "npm run check-format",
          "npm run check-lint",