name: CI/CD
on:
  push:
    branches: [master, main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing dependencies
        run: yarn install
      - name: Lint
        run: |
          yarn run lint
          yarn run format
          yarn run fix-lint
          yarn run check-format
          yarn run check-lint
      - name: Unit test
        run: yarn run test
      # - name: E2E tests
      #   run: yarn run cypress:headless
      - name: Build project
        run: yarn run build
