env:
  NODE_VERSION: 16

name: CI/CD
on:
  push:
    branches: [master, main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node "$RESOURCE_GROUP"
        uses: actions/setup-node@v2
        with:
          node-version: "$RESOURCE_GROUP"
      - name: Installing dependencies
        run: yarn install
      - name: Build project
        run: yarn run build
      - name: Store build into an artifact
        uses: actions/upload-artifact@v2
        with:
          name: .next
          path: .next

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node "$RESOURCE_GROUP"
        uses: actions/setup-node@v2
        with:
          node-version: "$RESOURCE_GROUP"
      - name: Installing dependencies
        run: yarn install
      - name: Download build from an artifact
        uses: actions/download-artifact@v2
        with:
          name: .next
          path: .next
      - name: Lint
        run: |
          yarn run lint
          yarn run format
          yarn run fix-lint
          yarn run check-format
          yarn run check-lint


  unit_test:
    needs: [build, lint]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node "$RESOURCE_GROUP"
        uses: actions/setup-node@v2
        with:
          node-version: "$RESOURCE_GROUP"
      - name: Installing dependencies
        run: yarn install
      - name: Download build from an artifact
        uses: actions/download-artifact@v2
        with:
          name: .next
          path: .next
      - name: Unit test
        run: yarn run test


  E2E_test:
    needs: [build, lint]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node "$RESOURCE_GROUP"
        uses: actions/setup-node@v2
        with:
          node-version: "$RESOURCE_GROUP"
      - name: Installing dependencies
        run: yarn install
      - name: Download build from an artifact
        uses: actions/download-artifact@v2
        with:
          name: .next
          path: .next
      - name: E2E tests
        run: yarn run cypress:headless
